### ISSUE TITLE
C4 Who is your daddy

### ISSUE THREAD

**Issue by DuskGTB** [yostane/cours-archi-logicielle#23]
![Diagramme sans nom drawio](https://github.com/yostane/cours-archi-logicielle/assets/73821723/e4787a67-40c2-4356-8698-169cccfa0d0a)

**Comment by omarDeCombat** [comment]
![C1](https://github.com/yostane/cours-archi-logicielle/assets/96078121/f97c57e1-7591-4208-9a95-ac59b8e24a68)
![C2](https://github.com/yostane/cours-archi-logicielle/assets/96078121/4048fcc1-227c-4640-bab5-dd310b889bb1)
![C3](https://github.com/yostane/cours-archi-logicielle/assets/96078121/12c8606d-e53a-4a7e-a3e9-cab9d27f5465)

**Comment by omarDeCombat** [comment]
![C3 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/b6d1a130-0369-4dbd-b5f4-c11b94f7f298)
![C2 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/4cb9b323-864b-4ed5-a50d-9b865accb37e)
![C1 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/75c32a9b-4d94-4289-83b0-5f6af542e022)

**Comment by omarDeCombat** [comment]
C1 :
![C1 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/efcc49af-0cd4-43bb-884c-441e6bd7b890)

C2:
![C2 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/7f13c0b6-8020-4f8b-92fe-22851b669103)

C3:
![C3 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/4316bae0-8107-49d6-8781-3f5fd4ed81b9)

**Comment by omarDeCombat** [comment]
C1:
![C1 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/ea49ca47-959e-438b-8b7b-c0fbe2f08f09)

C2:
![C2 drawio](https://github.com/yostane/cours-archi-logicielle/assets/96078121/1fee42ef-9c4f-4a04-b714-a17d7552c5c1)

C3:
![C3(1)](https://github.com/yostane/cours-archi-logicielle/assets/96078121/891e51c7-a11c-4789-ad6e-13f4cdeebe35)
